### ISSUE TITLE
Window not resizable

### ISSUE THREAD

**Issue by kevinyilmaz** [sonia-auv/build-simulation#6]
## Expected Behavior

I should be able to resize the window in windowed mode. 

## Current Behavior

Impossible to resize window in windowed mode.

![image](https://user-images.githubusercontent.com/104599594/166295500-b6a0208b-8d94-4f25-b149-0dffeac12623.png)

## Possible Solution

When generating the unity build, make sure to enable resizable feature.

## Comments

Icon in the right corner missing.

**Comment by Kam0ss** [comment]
This must be a problem with Ubuntu, because it works on Windows. We'll investigate this !

**Comment by kaowilly** [comment]
Problem is not apparent on Ubuntu on my end either.

**Comment by Kam0ss** [comment]
The problem appears when starting the simulation in fullscreen.
Close the simulation in windowed mode and open it again. It should work.
